### ISSUE TITLE
Add Shift Details

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#100]
**Purpose**

1. Touch up the frontend of the Add Shift Details modal
2. Add backend functionality to the modal

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Add the "Add Shift" button back onto the page
- [x] Touch up the Add Shift Details modal to align with the designs
- [ ] Add functionality to this modal! This means that on save, the database will update with this shift
- [ ] Create a PR for this ticket by 3 PM on Feb 19
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**

- [ ] we will get you resources for the backend part of this ticket
