### ISSUE TITLE
Reach out to Ben

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#101]
**TODO**

- [ ] Schedule a meeting with Ben
- [ ] Meet with Ben to discuss the mobile application
- [ ] Get mobile app up and running
