### ISSUE TITLE
Calendar Filters Functionality

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#106]
Link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/116

**Purpose**
To add fullstack functionality to the calendar filters modal

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] DO FIRST:
  - [x] Test last week's "Add Shift" button functionality
- [x] Add functionality to the Filters modal on the calendar page
  - [x] Filter by employment type
  - [ ] Filter by avalilability
  - [ ] Search by name
    - [x] Currently, the calendar filters button closes when you try to type in a name. Adjust the components so that you can type in a name
 
- [ ] Create a PR for this ticket by 3 PM on Feb 26
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
