### ISSUE TITLE
On-call Shifts

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#107]
**Purpose**
To display the "on-call" shift information on the Calendar page

**Designs**
[Desktop](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1156-2711&mode=design&t=F9WnDkxST62k3PQ0-0)

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Display the on-call shifts on the calendar page
- [x] On click of on-call shifts, display the info of the shift
 
- [x] Create a PR for this ticket by 3 PM on Feb 26
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
