### ISSUE TITLE
Alert confirmations

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#108]
**Purpose**
To add little "your change was saved" alerts to the application wherever there is a "save" button or "delete" button

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Add an alert saying "Your changes were saved" / "A profile was deleted" / "A profile was created"
  - [x] My Profile Page
    - [x] When a profile picture is uploaded
    - [x] When pronouns are updated
  - [x] Manage Employee Profile Page
    - [x] When you save changes to a profile
    - [x] When you create a new profile
    - [x] When you delete a profile
  - [ ] Bonus (depending on where the calendar page is at)
    - [ ] When you modify the state of one of your shifts
 
- [x] Create a PR for this ticket by 3 PM on Feb 26
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop

**Resources**
- [x] Material UI "Alert" [component](https://mui.com/material-ui/react-alert/#color)
