### ISSUE TITLE
Display full name

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#109]
**Purpose**
On the Calendar page, when you hover over a shift, display the full name of the person

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Get the name from the shift and display in Popper component
 
- [ ] Create a PR for this ticket by 3 PM on Feb 26
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**
- [ ] Material UI "Popper" [component](https://mui.com/material-ui/react-popover/)
