### ISSUE TITLE
Brushing up things

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#110]
**Purpose**
There are a lot of little things to work on during this ticket!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] My Profile Page
  - [x] Add fullstack functionality to "add pronouns"
- [ ] Employer Manage Profile Page
  - [ ] Currently only grabs 10 people from the database to display. We want ALL profiles to be displayed
  - [ ] After an employee profile has been updated/created/deleted, automatically refresh the page to display data
- [ ] Log in/log out
  - [ ] Update the logout button to only need 1 click (currently requires 2 clicks). May need to make a confirmation modal to achieve this.
   
- [ ] Create a PR for this ticket by 3 PM on Feb 26
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
