### ISSUE TITLE
Manage Profiles + Calendar Touchups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#113]
**Purpose**
There are a lot of little things to work on during this ticket!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Update the Manage Employee Profiles Page to refresh with the new data AND the alert
- [x] On the Calendar Page, edit the Choose Filters modal such that you can select a name without it closing   
- [x] Create a PR for this ticket by 3 PM on THURSDAY Feb 29
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
