### ISSUE TITLE
Fullstack touch ups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#118]
**Purpose**
There are several little things to work on during this ticket!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Pagination on the Manage Profiles Page
  - [x] Currently, the Manage Profiles Page only pulls 10 profiles. We want the page to pull all of the profiles and then display the first ten, and then the second ten on the next page, and so on
- [ ] Refreshing the calendar upon change
  - [ ] Currently, when a new shift is added, you have to manually refresh the website to see the new shift appear. Can you update the Calendar to refresh with new/modified shifts?
- [ ] Create a PR for this ticket by 3 PM on Monday March 11
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
