### ISSUE TITLE
Frontend touch ups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#119]
**Purpose**
There are several little things to work on during this ticket!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Update the icons of the Manage Profiles Page and Announcements page on the sidebar
 
- [x] Create a PR for this ticket by 3 PM on Monday March 11
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
