### ISSUE TITLE
Foundations (Naomi + Pamela)

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#12]
**Purpose**
To being using Material UI components on the frontend. We use Material UI so that we don't have to write our own CSS without any support. We can then use CSS to modify the component.

**TODO**

- [x] Create git branch according to style conventions
- [x] Make a button on app/page.tsx from material ui components
- [x] Update button text to "Login"
- [x] Bonus: update font, color, center your button on the page
- [x] Practice creating a PR

**Testing**
- [x] Desktop view
- [x] Mobile view

**Resources**
- [x] Material UI Button: https://mui.com/material-ui/react-button/
- [x] What is CSS: https://www.w3schools.com/css/css_intro.asp

**Notes**
```
git checkout dev # makes sure that you are currently on the dev branch
git pull # never hurts to pull
git checkout frontend #change "frontend" to "backend" if you are a backend dev
git pull # never hurts to pull
git merge dev # merges finalized code from dev branch onto your current local branch
git branch [frontend or backend]-[ticket #]-ticket-title # creates the new branch
** make changes to the file (for next week, you'll change files to create a button ** 
git add . # adds ALL the files you edited to the stage
git commit -m "[insert your message]" # saves your changes to your local branch
git push # pushes your changes to github 
```
