### ISSUE TITLE
Announcements page outline

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#120]
**Purpose**
To build out the Announcements page outline

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Announcements page
  - [x] Currently, the Announcement List Components are on the Announcements page. You can remove these from the page (the component will still exist, but it will come in later)
  - [x] Add a "background box"
  - [x] Add an "Add Announcemnt" Button
  - [x] Add the searching and filtering bar to the page

- [x] Create a PR for this ticket by 3 PM on Monday March 11
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
