### ISSUE TITLE
Announcements Backend

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#121]
**Purpose**
To build out the Announcements table

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Discuss what the announcements table should include based on the View Announcement [modal](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=582-1008&mode=design&t=7DWHlmLvqDrZdsZg-0)
- [x] Make the backend for the announcements table and relevant endpoints

- [ ] Create a PR for this ticket by 3 PM on Monday March 11
- [ ] Move this ticket into "Ready for Review"

**Testing**
