### ISSUE TITLE
Calendar: Add Shift Assign Employee Name Field

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#124]
**Purpose**
Assign Employee to shift is currently hardcoded to be 2 names. Should include all employee names in an autocomplete search

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**
- [ ] https://mui.com/material-ui/react-autocomplete/
