### ISSUE TITLE
Calendar: Add Shift On-call Shift

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#125]
**Purpose**
Currently, only adding a shift only works when adding something to "normal" shift table, not the the "on-call" shift table. As a result, we need to implement a new field on the Add Shift modal to mark to the shift is an hourly shift or an on-call shift.

Depending on the shift type, update the correct table with the shift data. Currently, all shifts are entered in the normal shift table, but we need the on-call shifts to be entered in the on-call shift table

**Design**
[Figma reference](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1460-3437&mode=design&t=8GlHzEjm5NJ9Gybr-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop: show that a new "on-call" shift was successfully added and the new "add shift" modal
