### ISSUE TITLE
Account Permissions: Assigned employee can cancel shift

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#126]
**Purpose**
Currently, any account can approve a cancel shift. We want to restrict this so that only the account assigned can cancel on a shift. This means modifying what buttons are available on a shift details page depending on the user's account.
So, if a shift is assigned, the approve/reject request buttons should only appear on the assigned employee's side

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop: show the same shift details page but logged in from the assigned employee's account vs a different employee's account
