### ISSUE TITLE
Account Permissions: Admins approve request

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#127]
**Purpose**
Currently, any account can approve a pending shift request. We want to restrict this so that only admins can approve this request. This means modifying what buttons are available on a shift details page depending on the user's account status (admin or not admin).
So, if a shift is pending, the approve/reject request buttons should only appear if the account is a manager

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop: show the same shift details page but logged in from an admin account vs an employee account
