### ISSUE TITLE
Refresh Page: Edit Employee Profile

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#129]
link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/139

**Purpose**
Currently, the Manage Employee Profile does not refresh after an employee's profile is edited. Upon saving the details of an employee, refresh the data so that it is accurately displayed

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
