### ISSUE TITLE
Refresh Page: Add Shift to Calendar

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#130]
**Purpose**
Currently, when you add a shift to the Calendar, it does not automatically refresh to display the data. Refresh the page automatically after a shift is added

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
