### ISSUE TITLE
Calendar: Add an Unassigned Shift

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#131]
link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/155

**Purpose**
We want to be able to add a shift that has not been assigned to an employee from the Add Shift modal

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
