### ISSUE TITLE
Calendar: Filters Logic

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#134]
**Purpose**
Currently all of the filters in the calendar are logically linked with "ORs" (or maybe "ANDs"?). Change the logic to be how someone might actually use to calendar filters

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
