### ISSUE TITLE
Create Schema (Sean + David)

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#14]
**Purpose**
Begin creating the User and Shift tables in our database

**TODO**
- [x] Create schema for User table (userId is a primary key (unique identifier))
- [x] Create schema for Shift table (shiftId is a primary key (unique identifier))
- [ ] Types such as time, status, and date should go in casa-myrna/app/types/types.tsx

**Resources**
Note: we are using Neon for our server, not Vercel, but this is still a great resource
- [x] https://vercel.com/guides/nextjs-prisma-postgres

Our database diagram:

![Image](https://github.com/elizabethfoster02/casa-myrna/assets/92819051/7e25a68b-6986-4493-b682-91b9b0b790fa)
