### ISSUE TITLE
Fullstack My Profile: Delete Profile Picture

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#140]
link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/156

**Purpose**
We want to be able to delete a profile picture! Here's a ticket to add that button. Also update this in the database

**Design**
[Figma reference](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1460-4357&mode=design&t=8GlHzEjm5NJ9Gybr-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
- [x] Mobile
