### ISSUE TITLE
Frontend: Cannot cancel shift modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#141]
**Purpose**
During user testing, the client mentioned that they do not want employees to be able to cancel their shifts all the way up until their shift begins. So, we want to set a limit on when someone can cancel their: if the moment they attempt the cancel is within 8 hours of the start of their shift, this modal should pop up and the shift should not be cancelable. For this ticket, design the modal (if you want to play around with the canceling within 8 hours pieces, go for it!)

**Design**
[Figma reference](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1460-4871&mode=design&t=8GlHzEjm5NJ9Gybr-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
- [x] Mobile
