### ISSUE TITLE
Input Validation: Shift time

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#142]
**Purpose**
We are at a point where we get to foolproof the user experience! Currently, the user has no restrictions to adding a shift (like, you can accidentally put the end time before the start time). Come up with other examples of invalid input. Validate the user input to something that makes sense.

If a user attempts to enter a time that doesn't make sense, bring up an alert (below)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop

**Resources**
[Alert](https://mui.com/material-ui/react-alert/)
