### ISSUE TITLE
Frontend Calendar: Admin Delete Shift

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#145]
Assignees:
Carly + Naomi

**Purpose**
We want to allow admins to delete a shift. On the Shift Details modal, add a "Delete Shift" button that appears only when admins view that shift. This is a frontend ticket to just make the button appear (in mobile and desktop) when an admin views Shift Details (if you want to make it fullstack, add functionality to this button).

**Designs**
[Add Shift Modal](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1460-3437&mode=design&t=aRiP3awxyhnXvB0w-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
- [x] Mobile
