### ISSUE TITLE
Backend: Sending Emails

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#147]
**Purpose**
When we want to be able to notify admin when a user edits a shift. Send an email if a user cancels/requests/approves a shifts. Some example phrasings for the emails are included below. Or at least look into feasibility

[SMTP settings and info for outlook ](https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040 )

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Send an email in the case of:
  - [x] Cancelation
    - [x] To all admin: "[Employee name] is unable to make their shift on [date/time]. The shift is now available for other employees to pick up."
    - [x] To the employee who canceled the shift: "You have canceled your shift on [date/time]. The shift is now available for other employees to pick up."
  - [x] Pending section
    - [x] To all admin: "[Employee name] has requested the shift on [date/time]. Approve this shift to assign it to [employee name]."
    - [x] To the employee who requested the shift: "You have requested the shift on [date/time]. A coordinator will approve or cancel this request."
  - [x] Pending => Approved shift
    - [x] To the employee whose shift was approved: "Your request for the shift on [date/time] has been approved."
  - [x] Pending => Canceled shift
    - [x] To the employee whose shift was rejected: "Your request for the shift on [date/time] has been rejected."
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
