### ISSUE TITLE
Frontend: Add shift time

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#158]
**Assignees**
Carly + Naomi

**Purpose**
We have a frontend update to the Add Shift Modal! Implementing this will allow more specific shift times to be entered

**Design**
[Shift modal](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=907-1125&mode=design&t=aRiP3awxyhnXvB0w-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
