### ISSUE TITLE
Backend: Add On-call Shift to Database

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#159]
**Purpose**
Currently, the Add On-Call Shift Modal does not add data to the correct table. When an on-call shift is created, add it to the on0-call database

**TODO**
- [ ] Claim this ticket by adding your name and moving to "In Progress"
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement the description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
