### ISSUE TITLE
Input Validation: Add Employee

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#160]
Link to PR: https://github.com/JumboCode/casa-myrna/pull/168

**Purpose**
When we add a new employee on the Manage Profiles page, we want to confirm that the email entered is a real email and the phone number entered is a real phone number.

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement description above
- [x] Create a PR for this ticket
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
