### ISSUE TITLE
Frontend: My Profile Add Pronouns

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#162]
**Purpose**
During use testing, we found that we needed to clean up how pronouns are edited on the My Profile page. We had a few ideas to improve this:
- adjust the transparency of the other fields (effectively graying them out) so that the Pronouns field stood out
- let the pronouns section just be textbox that could immediately be edited (no need to press the pen button, but the pen button and save changes button would still save the changes)

**Design**
[Reference](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1460-4357&mode=design&t=aRiP3awxyhnXvB0w-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
