### ISSUE TITLE
Fullstack: Edit Employee Profile Photo

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#163]
**Purpose**
Allow the admin to add and remove the profile photos of employees. Create the buttons on the Edit Employee modal and attach the endpoints (see example of endpoints on My Profile page)

**Design**
[Reference](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=437-1286&mode=design&t=aRiP3awxyhnXvB0w-0)

**TODO**
- [x] Claim this ticket by adding your name and moving to "In Progress"
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [ ] THEN create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Implement description above
- [ ] Create a PR for this ticket
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile
