### ISSUE TITLE
Create Sidebar

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#21]
Link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/26

**Purpose**
Create the sidebar that will be used throughout the application

**Design**

Desktop: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=50-413&mode=design&t=yB7HqDpRX1UBKR1V-0

Mobile: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=68-525&mode=design&t=yB7HqDpRX1UBKR1V-0

**TODO**

- [x] Make Announcement page
- [x] Make Calendar page
- [x] Make Group chat page
- [x] Make My Profile Page
- [x] Make Sidebar
- [x] Link pages to sidebar "onClick"
- [ ] If time, consider mobile (let Elizabeth know by 10/25 if possible)

**Testing**

- [x] Desktop
- [ ] *If time, Mobile

**Notes**

- [x] Follow the Manage Profile's set up to create a new page. label each page with just the title in plain html
- [ ] Splitting view by mobile vs desktop will require some independent research. Reach out with questions!

**Resources**

- [ ] Sidebar: https://mui.com/material-ui/react-menu/
- [ ] Icons: https://mui.com/material-ui/material-icons/
