### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#22]
**Purpose**
Create the Login page that will be used to enter the application

**Design**

Desktop: **Purpose**
Create the sidebar that will be used throughout the application

**Design**

Desktop: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=49-273&mode=design&t=yB7HqDpRX1UBKR1V-0

Mobile: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=49-285&mode=design&t=yB7HqDpRX1UBKR1V-0

**TODO**

- [ ] Include 
  - [ ] Graphic
  - [ ] Signin object from Clerk
  - [ ] Background gradient

**Testing**

- [ ] Desktop
- [ ] Mobile

**Resources**

- [ ] CSS Gradient Generator: https://cssgradient.io/
- [ ] Flex practice: https://flexboxfroggy.com/
