### ISSUE TITLE
User Endpoints

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#23]
**Purpose**
"Basic crud stuff for users" -Sean

**TODO**

- [ ] Set up various endpoints to access the user table
- [ ] Input fake user data
- [ ] Write unit tests
