### ISSUE TITLE
My Profile Page

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#27]
Link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/38

**Purpose**
Make the first complete "page" in the application, the My Profile page.

**Goal**
Complete the My Profile page so that is reflects the Figma design

**Design**
https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=63-587&mode=design&t=DNvWesv3t92D2hXR-0

**TODO**

- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Make edits to existing My Profile page
  - [x] Make Component
    - [x] Take existing code block and put it in a new file in the Components file
    - [x] Display the component in page.tsx in MyProfile folder
  - [x] Background Box
    - [x] adjust size of background box to change based on screen width (so it will "fit completely" on both mobile and desktop
    - [x] Update color to be the shade of grey in Figma
  - [x] Page Title
    - [x] Adjust position so that it stays in the gray box
  - [x] Profile Elements
    - [x] Update all page elements (except pronouns) to be boxes with text
      - [x] You can hardcode a word in each field. So I might hardcode "Elizabeth" under the "First Name" profile element
    - [x] Add space around each line of element in the profile box so it lays well on mobile
    - [x] Hint: use either "padding" or "margin" in CSS
- [x] Testing
  - [x] Mobile
  - [x] Desktop
- [ ] Add Sidebar component to page.tsx in My Profile file and ensure all of the above still looks good on Desktop
  - [ ] Test on Desktop
