### ISSUE TITLE
Shift modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#28]
**Purpose**
Display shift data from the calendar

**Goals**
To not only make the object, but get really good at useState

**Design**
https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=218-3561&mode=design&t=DNvWesv3t92D2hXR-0

**TODO**

- [ ] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Make a button on the Calendar page. Note: this won't be in the final draft, but we will use this button to open and close the shift modal
- [x] Make a modal with the MUI component
- [x] Display the shift information in the modal. Try and make the implementation look as similar to the design as possible. Ensure this looks good on
  - [x] Mobile
  - [x] Desktop
