### ISSUE TITLE
Profile List component

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#29]
**Purpose**
Create the employee profile component that can be displayed in a list on the Manage Profiles page

**Goal**
Make the component and figure out how multiple iterations using Typescript. Bonus: and display the information from different users

**Design**
https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=218-2776&mode=design&t=DNvWesv3t92D2hXR-0

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Create a new component in the components folder
- [x] Design the component with respect to the designs.
- [ ] Import and display the component on the Manage Profile page
- [ ] Hardcode an array of names to be displayed
- [ ] Use Typescript (ex. map) to display the component multiple times with the names from your array
  - [ ] Note: do not paste the element in multiple times

**Additional Notes**

- [x] This component does not need to be mobile-friendly and should not be tested on mobile
