### ISSUE TITLE
Sidebar Revisions

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#30]
[Casa Myrna (2).zip](https://github.com/elizabethfoster02/casa-myrna/files/13199482/Casa.Myrna.2.zip)

To make a mobile- and desktop-friendly sidebar

**Goal**
To learn about useState and create a sidebar that can be used in both mobile and desktop environments

**Design**
Desktop: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=68-592&mode=design&t=DNvWesv3t92D2hXR-0

Mobile: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=68-525&mode=design&t=DNvWesv3t92D2hXR-0

**TODO**

- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Build on the existing sidebar component
  - [x] Using the MUI Menu component, include the icons, titles, and links in the MenuList
  - [x] Update the icons with the images from a folder in the Slack channel
  - [x] Add logo with the images from a folder in the Slack channel
- [x] Desktop
  - [x] Modify the component so that the Sidebar is always open in Desktop
  - [x] Test
- [x] Mobile
  - [x] Add an icon to open and close the menu
  - [x] Test

**RESOURCES**

- [ ] what is responsiveness? https://www.youtube.com/watch?v=ZowbtOWOElY 
- [ ] for specifically mobile responsiveness: https://mui.com/material-ui/react-use-media-query/
