### ISSUE TITLE
Manage Profiles Page Outline

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#34]
Link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/45

**Purpose**

Outline the Manage Profile page. Run the app, find the page, and play around with placing MUI components

**Design**

- [ ] https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=401-607&mode=design&t=9GMHQNU5G5Nl49Fx-0

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Implement the other components on the page
  - [x] Title
  - [x] Add Employee button (no functionality)
  - [x] Search bar (no functionality)
    - [x] https://mui.com/material-ui/react-autocomplete/#search-input
  - [x] Search button (no functionality)
  - [x] Filter dropdown (list options, no functionality)
  - [x] Filter button (no functionality)
  - [x] Applied filters label
  - [ ] Leave a big box where employee profiles should go
  - [x] Add pagination (no functionality necessary)
    - [x] https://mui.com/material-ui/react-pagination/
- [x] Create a PR for this ticket by 3 PM on Sunday, November 12th
- [x] Move ticket to "Ready for Review"

**Testing**

- [x] Only necessary in desktop
