### ISSUE TITLE
Mobile Sidebar

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#36]
**Purpose**
Implement the mobile version of the sidebar and app background

**Goal**
Display the mobile menu/sidebar. If this only works on mobile, that is okay! We can go in and add the distinction between the mobile and desktop versions in the future

**Design**

- [ ] https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=68-525&mode=design&t=9GMHQNU5G5Nl49Fx-0

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Build off of existing Hamburger Menu and Sidebar
- [x] Add color to top bar
- [x] Add a bottom bar with "log out" button
- [x] Add gradient to background
- [x] Add and link page buttons
  - [x] Make sure to align padding/margins with the designs
- [ ] Create a PR for this ticket by 3 PM on Sunday, November 12th

**BONUS**

- [ ] Make the Mobile and Desktop Sidebar compatible depending on screenwidth

**RESOURCES**

- [ ] what is responsiveness? https://www.youtube.com/watch?v=ZowbtOWOElY 
- [ ] for specifically mobile responsiveness: https://mui.com/material-ui/react-use-media-query/
