### ISSUE TITLE
Repeated Components in Typescript

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#37]
**Purpose**
Explore Typescript in React! This is the part that actually feels like "code" lol

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Import and display the Profile List Component on the Manage Profile page 
  - [x] (the one Naomi worked on during the last sprint)
- [x] Hardcode an array of names to be displayed
- [x] Use Typescript (ex. map) to display the component multiple times with the names from your array
  - [x] Note: do not paste the element in multiple times
- [x] Create a PR for this ticket by 3 PM on Sunday, November 12th

**Bonus**

- [ ] If you happen to finish this ticket with time to spare, congrats on a light week of JumboCode! Catch up on sleep and your other homework
- [ ] If you are still itching for more webdev, I'll encourage you to further explore Typescript and its syntax by completing a [Leetcode problem ](https://leetcode.com/problems/valid-parentheses/)in Typescript (this is totally optional <3 and so not required)
