### ISSUE TITLE
Shift Table Endpoints

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#39]
**Purpose**

Write endpoints to the Shift table in the database

**TODO**

- [ ] Write CRUD command for shift objects
- [ ] Write GET commands based on a primary user and return a Shift Object
- [ ] Write GET commands based on a status and return a Shift Object
- [ ] Write GET commands based on a primary user and a status and return a Shift Object
- [ ] Create a PR for this ticket by 3 PM on Sunday, November 12th
- [ ] Move ticket to "ready for review"
