### ISSUE TITLE
Announcement List Component

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#40]
**Purpose**
Create the announcement component that can be displayed in a list on the Announcement page

**Goal**
Make the component and figure out how multiple iterations using Typescript. Bonus: and display the information from different Announcements

**Design**
Desktop: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=569-609&mode=design&t=1haUoUzjWwo2UOlx-0

Mobile: https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=580-902&mode=design&t=1haUoUzjWwo2UOlx-0

**TODO**
- [x] Fill out some forms
  - [x] Partner work + bondings: https://forms.gle/4VxNAw47u4fkuS3j8
  - [x] Admin feedback: https://forms.gle/CWCGSkBjQdQULt7c7
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Create a new component in the components folder
- [ ] Design the component with respect to the designs
- [x] Import and display the component on the Announcements page
  - [x] Test in mobile
  - [x] Test in desktop
- [x] Hardcode an array of names to be displayed
- [x] Use Typescript (ex. map) to display the component multiple times with the names from your array
  - [x] Note: do not paste the element in multiple times
- [x] Create a PR for this ticket by 3 PM on Sunday, November 19th
- [x] Move this ticket into "Ready for Dev"
