### ISSUE TITLE
Login Page w Clerk Resources

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#42]
**Purpose**
Make a functional Login page with the existing Clerk component. This will eventually allow us to log in / log out of the application with different types of user accounts

**Design**
https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=49-273&mode=design&t=OFapS8ByFz0kMI12-0

**TODO**
- [x] Fill out some forms
  - [x] Partner work + bondings: https://forms.gle/4VxNAw47u4fkuS3j8
  - [x] Admin feedback: https://forms.gle/CWCGSkBjQdQULt7c7
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Review designs
- [x] Review styling documentation
- [x] Review advice below and implement
- [x] Test
  - [ ] on mobile
  - [ ] on desktop
- [ ] Create a PR for this ticket by 3 PM on Sunday, November 19th
- [ ] Move this ticket into "Ready for Dev"

**Resouces**

- [ ] first make sure you are able to display the sign-in component on the page, you can use this resource to do so: [https://clerk.com/docs/components/authentication/sign-in](https://www.google.com/url?q=https://clerk.com/docs/components/authentication/sign-in&sa=D&source=docs&ust=1699821934311702&usg=AOvVaw1y0-EwjQ__Wx-fMlghRwWd) 
- [ ] now, scroll down to the section in this link [https://clerk.com/docs/components/customization/overview?utm_source=www.google.com&utm_medium=referral&utm_campaign=none](https://www.google.com/url?q=https://clerk.com/docs/components/customization/overview?utm_source%3Dwww.google.com%26utm_medium%3Dreferral%26utm_campaign%3Dnone&sa=D&source=docs&ust=1699821934311790&usg=AOvVaw34oy5BLS5eXONi-fuNOqiw) that says "Identify the underlying element"
- [ ] in this section, they are editing the "formButtonPrimary" attribute of the component, but say we want to edit the "Sign-in" font of the component. 
- [ ] use dev tools to hover over the sign-in component. notice how when you hover over the words "Sign in" on the components, it says "cl-headerTitle 🔒️ cl-internal-1vbdq0x", that means, if we use the code given in the second resource link above but change the "formButtonPrimary" to "headerTitle" the styling for the "Sign in" text on the component changes. 
- [ ] hopefully this helps, if you have any questions about the clarity of these instructions feel free to reach out to Nishika!
