### ISSUE TITLE
View Announcement Modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#43]
**Purpose**
When you click on an announcement from a list of announcements, this modal appears with the full message and details

**Designs**
[Desktop](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=582-1008&mode=design&t=1haUoUzjWwo2UOlx-0)
[Mobile](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=586-1310&mode=design&t=1haUoUzjWwo2UOlx-0)

**TODO**
- [ ] Fill out some forms
  - [ ] Partner work + bondings: https://forms.gle/4VxNAw47u4fkuS3j8
  - [ ] Admin feedback: https://forms.gle/CWCGSkBjQdQULt7c7
- [ ] Get updated with the codebase
  - [ ] git checkout frontend
  - [ ] git pull
  - [ ] then create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Review designs
- [ ] Make a button on the announcement page that says "view announcement"
- [ ] Implement a modal that opens onClick of the button
- [ ] Implement modal
  - [ ] Title
  - [ ] Name of user
  - [ ] Timestamp
  - [ ] Message
- [ ] Create a PR for this ticket by 3 PM on Sunday, November 19th
- [ ] Move this ticket to "Ready for Review"
