### ISSUE TITLE
Manage Profiles Page

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#44]
Link to PR: https://github.com/elizabethfoster02/casa-myrna/pull/50

**Purpose**
Build on the Manage Profiles Page Outline, Repeated Components in Typescript, and Profile List Component tickets to include a list of employee profiles in the Manage Profile page

This ticket is an example of frontend work in Typescript. Up until now, most of the work has been in HTML and CSS. This ticket really opens to door to Typescript's effects on the page with employee profile name displayed and pagination
opens the door to Typescript on a page

**TODO**
- [x] Fill out some forms
  - [x] Partner work + bondings: https://forms.gle/4VxNAw47u4fkuS3j8
  - [x] Admin feedback: https://forms.gle/CWCGSkBjQdQULt7c7
- [ ] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Review designs
- [x] Add list of employee profiles to Manage Profiles page
- [x] Adding functionality to pagination
  - [x] Make a really long list of employee profiles to display
  - [x] Implement pagination feature. Review MUI component documentation for details
- [ ] Move CSS code into new file according to new style standards
- [ ] Create a PR for this ticket by 3 PM on Sunday, November 19th
- [ ] Move this ticket to "Ready for Review"
