### ISSUE TITLE
Clerk data

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#47]
**Purpose**

**TODO**
- [x] Fill out some forms
  - [x] Partner work + bondings: https://forms.gle/4VxNAw47u4fkuS3j8
  - [x] Admin feedback: https://forms.gle/CWCGSkBjQdQULt7c7
- [x] Workshop metadata design with Nishika
- [ ] Rewrite 6 endpoints to call from Clerk database
- [x] Create fields in Clerk's metadata
  - [x] role
  - [x] pronouns
- [x] Make several users for testing purposes
  - [x] Include some regular employees
  - [ ] Include some admin
- [x] Start off by creating a user in the Clerk database
  - [x] https://clerk.com/docs/references/backend/overview

**Notes**
 
- [ ] Based on the documentation below, it looks like we won't need Prisma for communications to the Clerk database
  - [ ] https://clerk.com/docs/references/backend/overview&sa=D&source=docs&ust=1699821934321015&usg=AOvVaw16TqS5EvMo4JvFTSpFjiPl

**Resources**

- [ ] [https://clerk.com/docs/users/metadata#user-metadata](https://www.google.com/url?q=https://clerk.com/docs/users/metadata%23user-metadata&sa=D&source=docs&ust=1699821934319699&usg=AOvVaw3MUUfSxjQOWQ2dVdOAU_YX)
- [ ] Metadata: https://clerk.com/docs/users/metadata?utm_source=www.google.com&utm_medium=referral&utm_campaign=none#user-metadata
