### ISSUE TITLE
Design touch ups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#53]
**Goal**
Touch up the current components of the application and fit the pieces together in preparation for the demo on Dec. 8th

**TODO**

- [ ] lol idk if you want to fill this out yourself but here are some things i think we spoke about
- [x] incorporate sidebar into existing pages
- [ ] handle sidebar on mobile vs desktop
- [ ] map out what needs to be done to prep for logging in/logging out of the application
