### ISSUE TITLE
Announcement page + Manage Profile touch ups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#56]
**Purpose**
Make some slight modifications to the Manage Profiles page and build up the Announcements page. Right now, the Announcement List component is still not done, so swap in the Profile List Component as a placeholder (ask me questions about this if this description is confusing) on the Announcements page.

**Designs**

- [ ] [Manage Profiles page](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=401-607&mode=design&t=uiuCNUpeJ86D4IHt-0)
- [ ] [Announcements page (employee view)](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=569-609&mode=design&t=uiuCNUpeJ86D4IHt-0)
- [ ] [Announcements page (manager view)](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=569-769&mode=design&t=uiuCNUpeJ86D4IHt-0)

**TODO**
- [x] Fill out this [form](https://forms.gle/mJ4PUozcnnduLmLNA) for end of the semester poster
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Manage Profile Page
  - [x] Now that we have added the sidebar, some things shifted around in the flex layout. Adjust the search, filter, and add employee buttons so that they align
- [x] Announcement Page
  - [x] Build out the Announcement Page for desktop
  - [x] Build out the Announcement Page for mobile
- [x] Create a PR for this ticket by 3 PM on Sunday, December 3rd
- [x] Move this ticket into "Ready for Dev"

**Notes**
- [ ] If you get to adding pagination to the Announcements page, that's great, but I would prioritize a desktop and mobile-friendly Announcements page before pagination
- [ ] I know the profile list component will look messy on mobile, and that's okay
