### ISSUE TITLE
Sign in/sign out sessions

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#57]
**Purpose**
Add React Hooks to ensure the confirmed accounts are logging in and logging out of the application

**TODO**
- [x] Fill out this [form](https://forms.gle/mJ4PUozcnnduLmLNA) for end of the semester poster
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Build React Hooks into the application
- [x] Create a PR for this ticket by 4 PM on Sunday, December 10th
- [x] Move this ticket into "Ready for Dev"

**Resources**

- [x] for components related to signing in/out (scroll the sidebar for all of them): 
[https://clerk.com/docs/components/unstyled/sign-out-button](https://www.google.com/url?q=https://clerk.com/docs/components/unstyled/sign-out-button&sa=D&source=docs&ust=1700887222345820&usg=AOvVaw3dEC-9Jvv3Zorm-AAn7xKI)
- [x] for react hooks related to sessions (scroll the sidebar for all of them): 
[https://clerk.com/docs/references/react/use-auth](https://www.google.com/url?q=https://clerk.com/docs/references/react/use-auth&sa=D&source=docs&ust=1700887222346012&usg=AOvVaw1sIestKDkbzWgVcDiEddls)
- [x] global hooks: https://hosseinm-developer.medium.com/manage-state-with-react-hooks-how-to-use-react-global-hook-785331e5f1f
