### ISSUE TITLE
List Component Revisions

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#58]
**Goal**
Touch up both the Profile List Component and Announcement List Component

**Design**
[Announcement List Component (with edge cases)
](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=569-609&mode=design&t=uiuCNUpeJ86D4IHt-0)

**TODO**
- [x] Fill out this [form](https://forms.gle/mJ4PUozcnnduLmLNA) for end of the semester poster
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Announcement List Component
  - [x] Handle names/titles of different lengths
    - [x] see if there is a MUI component for this? we try to compile some resources
  - [x] Handle mobile and desktop versions
    - [x] consider using breakpoints to make the alignment smoother
- [ ] Profile List Component
  - [ ] Handle names/roles of different lengths
- [x] Create a PR for this ticket by 4 PM on Sunday, December 10th
- [x] Move this ticket into "Ready for Dev"
