### ISSUE TITLE
Add New Employee Modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#59]
**Purpose**
This builds off of the My Profile page and is what managers would fill out to add a new employee to their system

**Design**

- [ ] [Add Employee Profile](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=808-879&mode=design&t=uiuCNUpeJ86D4IHt-0)

**TODO**
- [x] Fill out this [form](https://forms.gle/mJ4PUozcnnduLmLNA) for end of the semester poster
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Add new modal attacked to the "add new employee" button on the Manage Profiles Page
- [x] Implement modal to reflect design
  - [ ] "Role" is selected from a dropdown menu implemented with the Select Component: https://mui.com/material-ui/react-select/
  - [ ] Add "Save Changes" button and close the modal "onClick"
- [ ] Create a PR for this ticket by 4 PM on Sunday, December 10th
- [ ] Move this ticket into "Ready for Dev"

**Notes**

- [ ] This does not need to be mobile-compatible, so testing in desktop is fine!

**Bonus**

- [ ] If you are really rolling, start working on the Edit Employee Page. It should be incredibly similar to the Add New Employee Page. The main difference to implement at this time is the delete employee" button
