### ISSUE TITLE
Creating OnCall Shift Table

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#60]
**Purpose**
Create the OnCall Shift Table and connect it to the User and Primary Shift table

**TODO**
- [ ] Fill out this [form](https://forms.gle/mJ4PUozcnnduLmLNA) for end of the semester poster
- [x] Get updated with the codebase
  - [x] git checkout backend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Follow the diagram above
- [x] Create fetch commands based on userId
- [x] Create fetch commands based on time range
- [ ] Create a PR for this ticket by 3 PM on Sunday, December 3rd
- [ ] Move this ticket into "Ready for Dev"

<img width="865" alt="image" src="https://github.com/elizabethfoster02/casa-myrna/assets/87954052/0c6ea599-65a5-44e8-9d90-35c766000663">
