### ISSUE TITLE
Add Shift Details

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#63]
**Purpose**
To build out the Add Shift Modal on the Calendar Page

**Design**
https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Initial-Design-Thoughts?type=design&node-id=907-1125&mode=design&t=apsIJ5gmAaIBYfmw-0

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Create an "Add Shift" button on the Calendar page
- [x] Create a modal that opens when you click "add shift"
- [x] Build out the design
  - [x] DO NOT implement the calendar that pops up when you select a date
  - [x] DO NOT implement the "On-Call Employee" field -- just delete from design
  - [x] DO implement the time dropdown menu in 30 minute increments
  - [x] DO implement the employee name dropdown menu
    - [x] hardcode a list of employee names to select
  - [x] DO implement the phone line drown (with numbers labeled 1-6)

- [ ] Create a PR for this ticket by TIME on DATE
- [ ] Move this ticket into "Ready for Dev"
