### ISSUE TITLE
Pull Shifts from Database

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#70]
**Purpose**
To pull the relevant shifts to present on the Calendar Page. This ticket will be complemented by a more frontend-focused ticket next week.

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Given a date/time, calculate the date/time range of shifts to display on Week view (12 AM Sunday - 11:59 PM Saturday)
- [x] Pull relevant shifts from database
  - [x] This means making fake data in the db to sort through
- [x] Bonus goals
  - [x] Pull shifts to display on Day view (12 AM - 11:59 PM of the day provided)
  - [x] Pull shifts to display on Month view (1st - last day of the month -- including edge cases for how a month ends)

- [x] Create a PR for this ticket by TIME on DATE
- [ ] Move this ticket into "Ready for Dev"
