### ISSUE TITLE
Bring Big Calendar into Project

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#71]
**Purpose**
To bring the Big Calendar API into the application! The goal is to just display the base calendar. Don't worry about displaying events.

**Design**
[Calendar page](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1033-7068&mode=design&t=7WTaI0CxlvLJ6SOs-0)

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [ ] Prepare the Calendar Page
  - [x] Update the title
  - [x] Remove the "add shift" button (we'll bring this component back later, but for now we can remove it from the page)
  - [x] Add a "Choose Filter" button (just for spacing purposes, it doesn't have to do anything)
  - [ ] Make an "add shift" button that aligns w designs
- [ ] Bring the Big Calendar into the Calendar page!
  - [ ] Align to match
    - [ ] Desktop designs
    - [ ] Mobile designs
  
- [ ] Create a PR for this ticket by TIME on DATE
- [ ] Move this ticket into "Ready for Dev"

**Resources**
- [ ] [Big Calendar API](https://jquense.github.io/react-big-calendar/examples/?path=/story/about-big-calendar--page)
