### ISSUE TITLE
Edit Employee Modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#72]
**Purpose**
From the Manage Profiles Page, to pull up an employee's profile, edit, and save the content! Note: this is a fullstack ticket 🥳

**Design**
[Edit Employee Profile page](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=437-1286&mode=design&t=7WTaI0CxlvLJ6SOs-0)

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
 
- [x] Build out the frontend of the modal
  - [x] When you click the "edit" button on a Profile List Component, this modal will pop up. Right now, there are 2 buttons that communicate "edit" on the Profile List Component, but for now, just make the modal pop open when you click the word "edit"
  - [x] Align the frontend designs with the Figma
    - [x] Note: the alignment of items should be very similar to the "Add Employee" modal, so use that as a resource
- [x] Display the current states of the field in the textboxes when the modal is open
- [x] Add functionality to the "save" button by updating the employee profile in Clerk
  - [x] Saving the information in the database is one step
  - [x] Immediately displaying the information on the frontend is another step. The list of employees will need to be refreshed with the new information
- [x] Bonus:
  - [x] Add functionality to the delete button in the frontend and backend
    - [x] Delete user from Clerk
    - [ ] Refresh the profiles displayed with the updated list from Clerk
  - [x] After a new employee is added, the list of employees needs to be refreshed such that the new employee is also displayed
  
- [x] Create a PR for this ticket by 3 PM on Feb 5
- [x] Move this ticket into "Ready for Dev"

**Testing**
- [x] Desktop
- [x] Show how a profile was updated (the before and after)
