### ISSUE TITLE
Align Profile List Component

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#73]
**Purpose**
Touch up the Profile List Component. There are two specific things that will really clean up this component.

**Design**
[Profile List Component](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=401-607&mode=design&t=7WTaI0CxlvLJ6SOs-0)
[Announcement List Component](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=569-609&mode=design&t=7WTaI0CxlvLJ6SOs-0)

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
 
- [x] Center alignment to left alignment
  - [x] Right now, the first names are all center-aligned with each other, the last names are all center-aligned with each other, and the roles are center-aligned with each other
  - [x] To clean this up, we want to shift things from center to left-aligned. The designs for the announcement list component have an example of this. This way, all the first names start at the same point, all of the last names start at the same point, and all of the roles start at the same point
  - [x] hint: look into the textAlign style attribute
  - [x] hint: you may have  to separate the first name, last name, role, and image into four separate divs + use the hint above
  - [x] hint: the code you want to focus on is on lines 35 - 49
- [x] Adding ellipses when a name gets too long
  - [x] We can display X number of characters in a name or role until the alignment of the name/role shifts. Reference the Announcement List Component for an example of this being used in code
  - [x] Depending on how you left-align the text, choose the number of characters to display per item

- [ ] Create a PR for this ticket by TIME on DATE
- [ ] Move this ticket into "Ready for Dev"

**Testing**
- [ ] Desktop

**Resources**
