### ISSUE TITLE
Upload Profile Pic Button

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#79]
**Purpose**
To update the "Upload Picture" button on the My Profile page to direct you to upload a file

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] On the "My Profile Page", update the "Upload Picture" button to direct you to open a file
- [x] Note: Don't change the styling of the button, just what happens when you click it
- [x] Note: this button does not have fullstack functionality yet. This means you can upload a photo, but it won't go anywhere/do anything
- [ ] Create a PR for this ticket by 3 PM on Feb 5
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop
- [x] Mobile

**Resources**
- [ ] [File upload MUI component](https://mui.com/material-ui/react-button/#file-upload)
