### ISSUE TITLE
Make Frontend Shift Object

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#80]
**Purpose**
To display (on the frontend) the shifts from the shift table

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Generate test data
  - [x] Note: only the month of January is displayed. Another group is working on getting the navigation of the calendar to work this week
  - [x] Types of test data
    - [x] Approved shifts
    - [x] Pending shifts
    - [x] Canceled shifts
    - [x] Overlapping shifts (3 concurrent shifts)
- [x] Display shifts on the Calendar page
  - [x] Do not hesitate to reach out if this is difficult
  - [x] Aslı wants to shifts to be a little transparent so you can see the lines of the calendar behind it
- [ ] On click, make the Shift Details Modal pop up
- [ ] Create a PR for this ticket by 3 PM on Feb 5
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Bonus: Mobile

**Resources**
- [ ] [Big Calendar API](https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/about-big-calendar--page)
