### ISSUE TITLE
Add Navigation Functionality to Calendar

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#81]
**Purpose**
To add navigational functionality to the Big Calendar. This will be a lot of copying code from their API documentation

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [ ] Things to get working
  - [ ] Views
    - [ ] Display current month (according to "Today") when pressing the "Month" button
    - [ ] Display current week (according to "Today") when pressing the "Week" button
    - [ ] Display current day (according to "Today") when pressing the "Day" button
  - [ ] Navigation
    - [ ] "Today" button
    - [ ] "Next" button
    - [ ] "Back" button

- [ ] Create a PR for this ticket by 3 PM on Feb 5
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile

**Resources**
- [ ] [Big Calendar API](https://jquense.github.io/react-big-calendar/examples/index.html?path=/story/about-big-calendar--page)
