### ISSUE TITLE
Add Account Page View Permissions

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#82]
**Purpose**
To manage which types of accounts get to view which pages

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [ ] Create "Admin View" for the sidebar
- [x] Confirm which types of accounts can be on which pages
  - [x] Calendar (Employee, Admin)
  - [x] Announcements (Employee, Admin)
  - [x] Group Chat (Employee, Admin)
  - [x] Manage Profiles (Admin ONLY)
  - [x] My Profile (Employee, Admin)

- [ ] Create a PR for this ticket by 3 PM on Feb 5
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile

**Resources**
- [ ] https://clerk.com/docs/components/protect

**Notes**
- [ ] We may need to give you guys "Employee" vs "Admin" emails to use to log in, so reach out!!
