### ISSUE TITLE
Fullstack Buttons

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#88]
**Purpose**
To add fullstack functionality to a couple of the buttons that are on the site. Should be a really fun ticket!!!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] My Profile Page
  - [x] Add pronouns
  - [ ] Upload Profile Picture
    - [ ] This builds off of Eliana/Yara's ticket from last week! The photo should be uploaded to Clerk
- [x] Delete Employee button
  - [ ] Add a modal to confirm if the user wants to delete an employee
- [ ] Bonus (do only if you want to explore/have the time):
  - [ ] Currently, you have to click the logout button twice for it to work. Can you explore why this is and maybe fix it? Do only if you have the time to explore!!  
- [ ] Create a PR for this ticket by 3 PM on Feb 12
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**
- [ ] [Delete employee modal](https://mui.com/joy-ui/react-modal/#alert-dialog)
