### ISSUE TITLE
Searching/filtering functionality on the Manage Profiles Page

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#89]
**Purpose**
To add searching/filtering functionality on the Manage Profiles Page.
Note: this might take 2 weeks to complete. If it does, that is okay! If you're thinking that it will take 2 weeks, send a message by Saturday, Feb 10th.

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout frontend
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Searching
- [x] Filtering
  - [x] Filter the list of employees based on the type of employee (per diem/part-time/full-time)
- [x] Searching
  - [x] Search for an employee based on their name
- [x] Create a PR for this ticket by 3 PM on Feb 12
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Desktop

**Resources**
- [ ] [Autocomplete search](https://mui.com/joy-ui/react-autocomplete/#search-input) (might be helpful ? not 100% sure)
