### ISSUE TITLE
Adding fullstack functionality to the add shift details modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#90]
**Purpose**
To add fullstack functionality to the add shift details modal. The frontend of the modal is already built. We are also only adding new shifts to the database, so you should only need to create new entries in the table. Explore how the frontend and backend interact with each other

**TODO**
- [ ] Get updated with the codebase
  - [ ] git checkout dev
  - [ ] git pull
  - [ ] then create a new branch as per usual
  - [ ] npm install (this updates your dependencies)
  - [ ] npm run dev
- [ ] Upon entering the details of a shift, create a new entry in the Shift table
- [ ] Create a PR for this ticket by 3 PM on Feb 12
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**
- [ ] Talk to Nishika during the team meeting to find the right endpoints!
