### ISSUE TITLE
Integrating Shift Modals

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#91]
**Purpose**
To integrate the shift modal object into the Calendar page. You once made the Shift Details object. Can you get this modal (with full details) to pop up on the click of a shift in the calendar? Then there are some variations of this object depending on

**Designs**

- [x] [Approved Shifts](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=218-3561&mode=design&t=30XLuTIn3sehBwtQ-0)
- [x] [Canceled Shift](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=241-703&mode=design&t=30XLuTIn3sehBwtQ-0)
- [ ] [Pending Shift (normal employee view)](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=241-777&mode=design&t=30XLuTIn3sehBwtQ-0)
- [ ] [Pending Shift (admin view)](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=241-852&mode=design&t=30XLuTIn3sehBwtQ-0)

**TODO**
- [x] ******Create a branch from your previous week's ticket******
  - [x] git checkout fullstack-80-make-frontend-shift-object
  - [x] then create a new branch as per usual
  - [x] npm run dev
- [x] Make Shift Details modal pop up on click of a shift in the calendar page
- [x] Have Shift Details modal display the status of the shift
  - [x] Approved state
  - [x] Pending state
  - [x] Canceled state
- [ ] Modify the state of the shift based on the buttons
- [ ] Depending on the state of the shift, modify the buttons of the Shift Details to display correctly
- [ ] Bonus:
  - [ ] Depending on if the user is an Coordinator or a (normal) employee, change the Pending ticket to reflect which button should be there
- [ ] Create a PR for this ticket by 3 PM on Feb 12
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
- [ ] Mobile

**Resources**
- [ ] [Autocomplete search](https://mui.com/joy-ui/react-autocomplete/#search-input) (might be helpful ? not 100% sure)
