### ISSUE TITLE
Calendar Filters Modal

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#92]
**Purpose**
To make the desktop frontend for the Filters modal on the Calendar Page. Note: the mobile version will come later and be completely different, so you only have to implement the designs for desktop

**Designs**
- [x] [Desktop](https://www.figma.com/file/8kPY1C2UNsyWYtl59b6rwr/Casa-Myrna-Design?type=design&node-id=1033-5325&mode=design&t=30XLuTIn3sehBwtQ-0)

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] then create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Open a new Modal on click of the Choose Filters button
- [x] Implement Desktop Version
- [x] Create a PR for this ticket by 3 PM on Feb 12
- [x] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop

**Resources**
- [ ] [Autocomplete search](https://mui.com/joy-ui/react-autocomplete/#search-input) (might be helpful ? not 100% sure)
