### ISSUE TITLE
Sending emails

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#95]
**Purpose**
Send emails to certain employees based on actions performed

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev
- [x] Explore the Clerk API for sending emails!
- [x] Help Bill wrap his previous ticket. There are some hefty blackened things going on
- [x] Get on the same page about how the Shift Table works
- [x] Create endpoints for updating an entry in the shift table
  - [x] update name and status when a shift changes status. Let us know if you want to discuss what this relationship looks like!
  - [x] ex: Approved -> Open -> Pending 
- [ ] Along with updating the table entry, create an endpoint to send an email to admin users that the shift's status was updated (and include what the new status is)
- [ ] Create a PR for this ticket by 3 PM on Feb 19
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Show the emails you've received when shifts have been moved to different statuses

**Resources**
- [ ] [Clerk email documentation](https://clerk.com/docs/references/backend/emails/create-email)
- [ ] tell them to use a test name for “fromEmailName” - from Nishika
