### ISSUE TITLE
Profile Pictures

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#96]
**Purpose**
Make user profile pictures appear throughout the application!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Upload Profile Picture
  - [x] The photo should be uploaded to Clerk
- [x] Have Profile Photo appear
  - [x] My Profile Page
  - [ ] Profile List Component on the Manage Employee Profiles page

- [ ] Create a PR for this ticket by 3 PM on Feb 19
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
