### ISSUE TITLE
Frontend Touchups

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#98]
**Purpose**
There have been a couple of frontend touch-ups that we've been putting off! There are several small things to work on

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] My Profile page
  - [x] Swap where the lastName and pronoun fields are (so the top reads last name, first name)
- [ ] Employee Profile page
  - [ ] There are currently 2 "edit" buttons: an "EDIT" and a pencil. We want to get ride of the "EDIT" and just have the pencil icon, but keep the functionality
- [ ] Calendar page
  - [ ] In the "Choose Filters" modal, if you try to type in a name, the modal closes (so you can't type in a name). Can you figure out why this is and update it?

- [ ] Create a PR for this ticket by 3 PM on Feb 19
- [ ] Move this ticket into "Ready for Review"

**Testing**
- [ ] Desktop
