### ISSUE TITLE
Mobile Choose Filters Button

### ISSUE THREAD

**Issue by elizabethfoster02** [JumboCode/casa-myrna#99]
**Purpose**
On the Mobile Calendar page, the Choose Filters button ends up hanging off of the screen. This ticket is to reposition it. Hopefully, this is a short ticket for you. Good luck with filming!

**TODO**
- [x] Get updated with the codebase
  - [x] git checkout dev
  - [x] git pull
  - [x] THEN create a new branch as per usual
  - [x] npm install (this updates your dependencies)
  - [x] npm run dev

- [x] Reposition the Choose Filters button on mobile to align with the designs.

- [x] Create a PR for this ticket by 3 PM on Feb 19
- [x] Move this ticket into "Ready for Review"

**Testing**
- [x] Mobile
- [x] Desktop (to make sure nothing changed)
